### ISSUE TITLE
Not looking good on Small Sizes

### ISSUE THREAD

**Issue by carlos0202** [chadkuehn/BootstrapPager#2]
Is there a workaround to keep the pager looking good on mobile screens and such?

Thanks for all!!!

**Comment by chadkuehn** [comment]
The issue you mention appears to be the wrapping of the pager.  You can add this code at the end of your document to prevent wrapping:

```css
	<style>
	.dataTables_footer{white-space:nowrap;}
	.dataTables_info{display:inline-block;}
	.dataTables_paginate{display:inline-block;}
	</style>
```
```javascript
	<script>
	$(".dataTables_wrapper").find(".dataTables_info, .dataTables_paginate").wrapAll('<div class="dataTables_footer">');
	</script>
```
I don't know if that improves anything for you.  I probably need to consider making it a bit more responsive and shrink the space between buttons based on screen size and media queries.

![2015-05-26 10_17_21](https://cloud.githubusercontent.com/assets/5702928/7815895/d2713aac-0390-11e5-9d65-951c5aeed198.png)
